<?php echo $this->doctype(); ?>

<html lang="en" class="wvusUikit">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Zend2 '. $this->translate('Protofisch'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/protofisch.css'))
                        ->prependStylesheet($this->basePath('uikit/css/wvus.uikit.min.css'))
                         ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('uikit/js/wvus.uikit.min.js')) 
            ->prependFile($this->basePath('uikit/js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <div class="wrapper">
            <div class="row">
                <div class="app col-md-8  panel panel-default col-md-offset-2 col-xs-12">
                    <div class="panel-body">
                        <div class="protofisch">
                            <img src="<?php echo $this->basePath('images/fisch-icon.png') ?>" height="75">
                            <h1>Proto-Fisch</h1>
                        </div>

                        <p>A Simple CRUD App</p>
                        <?php echo $this->content; ?>                            

                    </div>          
                </div>
            </div>
        </div>        
    </body>
</html>
